version: "3"
services:
  redis:
    image: redis
    restart: 'no'
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 2s
      retries: 3
  service:
    build:
      context: ../.
      dockerfile: deployments/Dockerfile
    env_file: environment
    #volumes:
    #  - ../..:/opt/service
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
  integration_test:
    build:
      context: ../.
      dockerfile: deployments/DockerfileTest
    env_file: environment
    depends_on:
      - service
